export const educationDatabase = [
    {title: 'Informatics: Programming and Systems Architecture', degree: 'Master of Science', school: 'University of Oslo', year: '2025 - 2028', description: ''},
    {title: 'Software Engineering', degree: 'Bachelor of Engineering', school: 'Oslo Metropolitan University', year: '2022 - 2025', description: 'The program covers a wide range of topics within Computer Science and Software Engineering, such as mathematics, physics, programming, algorithms and datastructures, databases, web development, app development, software testing, cyber security, computer networks, computer architecture, operating systems and more.'},
    {title: 'Pre-Engineering', degree: '1-year course', school: 'Oslo Metropolitan University', year: '2019 - 2020', description: 'Required to be able to apply for the Engineering program.'},
    {title: 'Computer Electronics', degree: 'Trade Certificate', school: 'Elvebakken VGS, Sogn VGS and Intility', year: '2009 - 2014', description: 'The first three years covered topics such as electrical systems, electronics, programming, servers, computer hardware, computer architecture and computer networks. The last 18 months were an apprenticeship at Intility, where I worked as an IT support technician.'},
];

export const experienceDatabase = [
    {title: 'Consultant', company: 'Decisive AS', year: '2025 - Present', description: 'Software Develpment'},
    {title: 'Incident Responder', company: 'Intility', year: '2017 - 2022', description: 'IT Operations, monitoring and incident management of network and server infrastructure and a wide range of business applications and services. Handle operational incidents and alerts in the monitoring system, troubleshooting, fixing or escalating complex and critical errors. E.g. downtime, resource usage or other issues with networks, servers and various applications and services. Other tasks included deleting servers, changing server resources, restoring servers or files from backup. Worked with technologies such as Windows Server, Linux, Cisco, VMware and Azure. Training of support technicians in monitoring and incident management.'},
    {title: 'Senior Technician', company: 'Intility', year: '2015 - 2017', description: 'Distribute tickets to and assist support-technicians and troubleshoot more complex issues. Mentoring apprentices and new employees. 3 months in Auckland and 12 months at Intility’s office in Singapore. Contributed to establishing 24/7 support, monitoring and incident management from the Singapore office. On-site support for client in Singapore and contributed on-site during onboarding of a new client office in Hong Kong.'},
    {title: 'Technician', company: 'Intility', year: '2014 - 2015', description: 'Technical support with specialization in the business applications of Intility`s customers. Training of apprentices and new employees.'},
    {title: 'Technical Apprentice', company: 'Intility', year: '2012 - 2014', description: 'Apprenticeship. Technical support via phone, e-mail and chat.'},
];

export const projectDatabase = [
    {title: '3D World', github: 'https://github.com/vetlelg/3D-World', url: '/3D_World_WebGLBuild/game.html', organization: 'Personal project', year: 'Spring 2025', description: 'I´m just playing around with 3D in Unity. A simple open 3D world created in Unity.', technologies: ['Unity', 'C#']},
    {title: 'Top Down Shooter', github: 'https://github.com/vetlelg/TopDownShooter', url: '/WebGLBuild/game.html', organization: 'Personal project', year: 'Spring 2025', description: 'A 2D top-down shooter game made with Unity.', technologies: ['Unity', 'C#']},
    {title: 'Bachelor´s project', github: '/', url: '', organization: 'Decisive AS', year: 'Spring 2025', description: 'One of Decisive’s clients uses an HTTP-based solution for one-way message distribution between applications in an event-driven architecture and cannot use middleware solutions such as Kafka or ActiveMQ. The current solution is pull-based and has some performance limitations. Our task was to test and implement a new solution with push-based technologies to improve performance. Decisive wanted to test R2DBC for push-based database communication, as well as long polling and server-sent events for push-based HTTP communication. We then evaluated whether long polling or server-sent events was best suited. The solution consists of a server, clients, and a database running in Docker containers, developed in Kotlin and Spring WebFlux, with PostgreSQL as the database.', technologies: ['Kotlin', 'Spring Webflux', 'Reactive Programming', 'PostgreSQL', 'R2DBC', 'Docker', 'Event-driven Architecture'] },
    {title: 'ITPE3200 - Web Applications', github: 'https://github.com/vetlelg/ITPE3200-Web-Applications', url: '', organization: 'Oslo Metropolitan University', year: 'Fall 2024', description: 'School project developing a map application for registering and storing markers with location data, images, and comments. Initially built in ASP.NET MVC, later recreated with React and ASP.NET Web API. Implemented with Google Maps JavaScript API, EF Core, and SQLite. Designed with Bootstrap and CSS. Full-stack solution including input validation, error handling, logging, unit testing, cookie-based authentication and authorization.', technologies: ['React', 'JavaScript', 'ASP.NET', 'EF Core', 'C#', 'Bootstrap', 'SQLite', 'HTML/CSS', 'Google Maps JavaScript API']},
    {title: 'DAVE3600 - App Development', github: 'https://github.com/vetlelg/DAVE3600-App-Development', url: '', organization: 'Oslo Metropolitan University', year: 'Fall 2024', description: 'School projects in Android app development using Java. Created an app for simple math exercises, an app for storing birthdays/phone numbers with automatic SMS sending, and an app for saving map markers in an SQL database using the Google Maps Android SDK.', technologies: ['Java', 'Android', 'Google Maps Android SDK']},
    {title: 'vetlelg.com', github: 'https://github.com/vetlelg/vetlelg-frontend', url: '', organization: 'Personal project', year: 'Fall 2024', description: 'Personal website built with React, Bootstrap, and CSS. Hosted on Azure with automatic deployment with GitHub Actions on new commits.', technologies: ['React', 'Bootstrap', 'JavaScript', 'HTML/CSS', 'Azure'] },
    {title: 'DATA2410 - Networking', github: 'https://github.com/vetlelg/DATA2410-DRTP', url: '', organization: 'Oslo Metropolitan University', year: 'Spring 2024', description: 'School project in socket programming with Python. A file transfer application for sending files over a network between client and server. It uses UDP and implements TCP-like functionality at the application layer, including a three-way handshake for connection setup, Go-Back-N sliding window protocol for data transfer, and a two-way handshake for connection termination.', technologies: ['Python', 'Socket library']},
    {title: 'DATA1700 - Webprogramming', github: 'https://github.com/vetlelg/DATA1700-Webprogramming', url: '', organization: 'Oslo Metropolitan University', year: 'Spring 2023', description: 'School projects in full-stack web development with Java Spring Boot, JavaScript, Bootstrap, and SQL. The course also covered client- and server-side input validation, error handling, logging, cookie-based authentication, sessions, and password hashing and salting.', technologies: ['Java', 'Spring Boot', 'SQLite', 'JavaScript', 'Bootstrap'] },
    {title: 'DATA1200 - Inclusive Web Design', github: 'https://github.com/vetlelg/final-assignment', url: '', organization: 'Oslo Metropolitan University', year: 'Fall 2022', description: 'School project in web development and inclusive design. The course covered topics such as HTML, CSS Box Model, Flexbox, Grid and WCAG.', technologies: ['HTML', 'CSS']},
    {title: 'The Fountain of Objects', github: 'https://github.com/vetlelg/csharpplayersguide/tree/main/bossbattles/TheFountainOfObjects', url: '', organization: 'Personal Project', year: 'Fall 2021', description: 'A fun and simple console game I made when learning C#. This was part of the book "The C# Player´s Guide" by RB Whitaker.', technologies: ['C#']},
    {title: 'Snake', github: 'https://github.com/vetlelg/sfml-snake', url: '', organization: 'Personal Project', year: 'Fall 2017', description: 'My first object-oriented programming project I created when trying to learn C++', technologies: ['C++', 'SFML']},
];